carts/urls.py
from django.urls import path
from carts.views import AddToCartView, RemoveFromCartView

urlpatterns = [
    path("<int:pk>/add_to_cart", AddToCartView.as_view(), name="add-to-cart"),
    path("<int:pk>/remove_from_cart",
         RemoveFromCartView.as_view(), name="remove-from-cart"),
]

eatsy/urls.py
from django.contrib import admin
from django.urls import path, include
from eatsy.views import HomePageView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', HomePageView.as_view(), name="home"),
    path('restaurants/', include('restaurants.urls')),
    path('carts/', include("carts.urls")),
    path('orders/', include("orders.urls")),
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

restaurants/urls.py
from django.urls import path
from restaurants.views import RestaurantListView, RestaurantDetailView

urlpatterns = [
    path("", RestaurantListView.as_view(), name="restaurant-list"),
    path("<slug:slug>/", RestaurantDetailView.as_view(), name="restaurant-detail"),
]

restaurants/models.py
from django.db import models
from django.utils.text import slugify
from PIL import Image


class Restaurant(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True, max_length=255)
    description = models.TextField()
    address = models.CharField(max_length=255)
    contact_number = models.CharField(max_length=15)
    image = models.ImageField(
        upload_to='restaurant_images/', null=True, blank=True)
    is_open = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()

    def __str__(self):
        return self.name


class Menu(models.Model):
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.DecimalField(max_digits=8, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='menu_images/')

    def __str__(self):
        return self.name

restaurants/views.py
from restaurants.models import Restaurant
from django.views.generic import DetailView, ListView
from carts.models import CartItem


class RestaurantListView(ListView):
    model = Restaurant
    paginate_by = 10


class RestaurantDetailView(DetailView):
    model = Restaurant

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        if user.is_authenticated:
            cart_items = CartItem.objects.filter(
                cart__user=user,
                menu__restaurant=self.object
            )

            total_amount = sum(
                item.quantity * item.menu.price for item in cart_items)

            context['cart_items'] = cart_items
            context['total_amount'] = total_amount
        return context

restaurants/templates/restaurants/restaurant_detail.html
{% extends "base.html" %}


{% block head %}
<nav aria-label="breadcrumb" class="my-2">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
        <li class="breadcrumb-item"><a href="{% url 'restaurant-list' %}">Restaurants</a></li>
        <li class="breadcrumb-item">{{ restaurant.name }}</li>
    </ol>
</nav>


<div class="row g-2">
    <div class="col-5">
        <h1 class="display-4">{{ object.name }}</h1>

        {% if object.is_open %}
        <p class="text-success fw-bold">Open Now</p>
        {% endif %}

        <p class="text-muted"><i class="bi bi-telephone-fill"></i> {{ object.contact_number }}</p>
        <p class="text-muted"><i class="bi bi-geo-alt-fill"></i> {{ object.address }}</p>
    </div>
    <div class="col">
        <img src="\media\restaurant_images\63f33764658fce51b5cf4b5686610a38.avif" class="img-fluid rounded" alt="...">
    </div>
</div>


<ul class="nav nav-underline my-2">
    <li class="nav-item">
        <a class="nav-link active">Menu</a>
    </li>

    <li class="nav-item">
        <a class="nav-link" href="#">Reviews</a>
    </li>
</ul>




<div class="row">
    <div class="col-md-8">
        <div class="row row-cols-1 g-2">
            {% for menu in object.menu_set.all %}
            <div class="col">
                <div class="card">
                    <div class="row g-0 align-items-center">
                        <div class="col-auto">
                            <img src="{{ menu.image.url }}" class="img-fluid rounded-start">
                        </div>
                        <div class="col">
                            <div class="card-body">
                                <h5 class="card-title">{{ menu.name }}</h5>
                                <p class="card-text my-0">₹{{ menu.price }}</p>
                                <p class="card-text my-0">
                                    <small class="text-body-secondary">{{ menu.description}}</small>
                                </p>
                                <p class="card-text">
                                    <small class="badge text-bg-secondary">{{ menu.category.name}}
                                    </small>
                                </p>

                                <form method="POST" action="{% url 'add-to-cart' menu.pk %}?next={{ request.path }}">
                                    {% csrf_token %}
                                    <div class="input-group w-25">
                                        <input type="number" name="quantity" value="1" min="1"
                                            class="form-control form-control-sm" aria-describedby="submit">

                                        <button type="submit" id="submit"
                                            class="input-group-text btn btn-sm btn-primary">Add to
                                            Cart</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% empty %}
            <p>Sorry, no menus found.</p>
            {% endfor %}
        </div>
    </div>
    <div class="col-md-4">
        {% if user.is_authenticated %}
        <h2 class="display-6">Your Cart</h2>
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
        {% endif %}
        <div class="row row-cols-1 g-2">
            {% for cart_item in cart_items %}
            <div class="col">
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex justify-content-between">
                            <p>{{ cart_item.quantity }} x {{ cart_item.menu.name }}</p>
                            <p>₹{{ cart_item.menu.price }}</p>
                        </div>
                        <a href="{% url 'remove-from-cart' cart_item.pk %}?next={{ request.path }}">Remove</a>
                    </div>
                </div>
            </div>
            {% empty %}
            <p class="text-muted">Your cart is empty.</p>
            {% endfor %}
            <hr>
            {% if cart_items %}
            <div class="">
                <div class="d-flex justify-content-between">
                    <p class="fs-5 fw-bold">Total Amount</p>
                    <p class="fs-5 fw-bold">₹{{total_amount}}</p>
                </div>


                <form method="POST" action="{% url 'place-order' object.slug %}">
                    {% csrf_token %}
                    <div class="d-grid gap-2">
                        <button type="submit" id="submit" class="btn btn-warning btn-lg">Place Order</button>
                    </div>
                </form>

            </div>
            {% endif %}
        </div>

        {% else %}

        <p>Please <a href="{% url 'login' %}">log in</a> to view your cart.</p>
        {% endif %}
    </div>
</div>
{% endblock %}

restaurants/templates/restaurants/restaurant_list.html
{% extends "no_sidebar_base.html" %}



{% block head %}
<h1 class="display-6 my-5"> Best Food in Mumbai</h1>
{% endblock %}

{% block content %}
<style>
    .card {
        transition: box-shadow 0.3s ease-in-out;
    }

    .card:hover {
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
    }
</style>


<div class="row row-cols-1 row-cols-md-5 g-3">
    {% for restaurant in page_obj %}
    <div class="col">
        <a href="{% url 'restaurant-detail' slug=restaurant.slug %}" class="text-decoration-none">
            <div class="card rounded-2">
                <img src="{{ restaurant.image.url }}" class="card-img-top" alt="Restaurant Image">
                <div class="card-body">
                    <div class="d-flex justify-content-between align-items-center">
                        <h5 class="card-title">{{ restaurant.name }}</h5>
                        <span class="badge text-bg-success">4.2 <i class="bi bi-star-fill"></i></span>
                    </div>

                    <div class="d-flex justify-content-between align-items-center">
                        <p class="text-muted">{{ restaurant.address }}</p>
                        <p class="text-muted">₹150 for two</p>
                    </div>
                </div>
            </div>
        </a>
    </div>
    {% empty %}
    <p>Sorry, no posts found.</p>
    {% endfor %}
</div>

{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation example" class="mt-5">
    <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1">First</a></li>
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
        {% endif %}

        {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last</a></li>
        {% endif %}
    </ul>
</nav>
{% endif %}
{% endblock %}


{% block sidebar %}
{% endblock %}