accounts/urls.py
from django.urls import path
from accounts.views import RegisterView, ProfileView, ProfileUpdateView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordResetView
urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path("profile/edit/", ProfileUpdateView.as_view(), name="profile-edit"),
    path('password_reset/', PasswordResetView.as_view(
        html_email_template_name='registration/password_reset_email.html'), name='password_reset'),
]

carts/urls.py
from django.urls import path
from carts.views import AddToCartView, RemoveFromCartView

urlpatterns = [
    path("<int:pk>/add_to_cart", AddToCartView.as_view(), name="add-to-cart"),
    path("<int:pk>/remove_from_cart",
         RemoveFromCartView.as_view(), name="remove-from-cart"),
]

eatsy/urls.py
from django.contrib import admin
from django.urls import path, include
from eatsy.views import HomePageView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', HomePageView.as_view(), name="home"),
    path('restaurants/', include('restaurants.urls')),
    path('carts/', include("carts.urls")),
    path('orders/', include("orders.urls")),
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class Account(AbstractUser):
    bio = models.TextField(blank=True, null=True)
    avatar = models.ImageField(
        upload_to='avatars/',
        blank=True,
        null=True,
        default='avatars/default_avatar.png'
    )

    SEX_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other'),
    )

    date_of_birth = models.DateField(null=True, blank=True)
    sex = models.CharField(
        max_length=1, choices=SEX_CHOICES, blank=True, null=True)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

User = get_user_model()


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=30, required=True)

    class Meta(UserCreationForm.Meta):
        model = User
        fields = UserCreationForm.Meta.fields + \
            ("email", "first_name", "last_name")

accounts/views.py
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from django.views.generic import CreateView
from accounts.forms import RegistrationForm
from accounts.models import Account
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import login, authenticate
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.auth import get_user_model

User = get_user_model()


class RegisterView(CreateView):
    template_name = "accounts/register.html"
    model = User
    form_class = RegistrationForm
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        response = super().form_valid(form)
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')
        user = authenticate(self.request, username=username, password=password)
        if user is not None:
            login(self.request, user)
        return response


class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = "accounts/profile.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        return context


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = Account
    fields = ["first_name", "last_name",
              "date_of_birth", "bio", "avatar", "sex"]
    success_url = reverse_lazy('profile')

    def get_object(self, queryset=None):
        return self.request.user

accounts/templates/accounts/account_form.html
{% extends "no_sidebar_base.html" %}


{% block content %}
<div class="card mx-auto" style="width: 460px;">
    <div class="card-body">
        <h1 class="display-6 mb-4">Edit Profile</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row mb-3">
                <div class="col-md-6">
                    <div class="form-floating">
                        <input type="text" value="{{ form.first_name.value|default_if_none:'' }}"
                            class="form-control {% if form.first_name.errors %} is-invalid {% endif %}"
                            id="id_first_name" name="first_name" placeholder="First Name">
                        <label for="id_first_name">First Name</label>
                        {% if form.first_name.errors %}
                        <div class="invalid-feedback">
                            {% for error in form.first_name.errors %}
                            {{ error }}
                            {% endfor %}
                        </div>
                        {% endif %}
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-floating">
                        <input type="text" value="{{ form.last_name.value|default_if_none:'' }}"
                            class="form-control {% if form.last_name.errors %} is-invalid {% endif %}" id="id_last_name"
                            name="last_name" placeholder="Last Name">
                        <label for="id_last_name">Last Name</label>
                        {% if form.last_name.errors %}
                        <div class="invalid-feedback">
                            {% for error in form.last_name.errors %}
                            {{ error }}
                            {% endfor %}
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>

            <div class="form-floating mb-3">
                <input type="date" class="form-control {% if form.date_of_birth.errors %} is-invalid {% endif %}"
                    id="id_date_of_birth" name="date_of_birth" value="{{ form.date_of_birth.value|date:'Y-m-d' }}">
                <label for="id_date_of_birth">Date of Birth</label>
                {% if form.date_of_birth.errors %}
                <div class="invalid-feedback">
                    {% for error in form.date_of_birth.errors %}
                    {{ error }}
                    {% endfor %}
                </div>
                {% endif %}
            </div>

            <div class="form-floating mb-3">
                <select class="form-select {% if form.sex.errors %} is-invalid {% endif %}" id="id_sex" name="sex">
                    {% for value, label in form.sex.field.choices %}
                    {% if form.sex.value == value %}
                    <option value="{{ value }}" selected>{{ label }}</option>
                    {% else %}
                    <option value="{{ value }}">{{ label }}</option>
                    {% endif %}
                    {% endfor %}
                </select>
                <label for="id_sex">Sex</label>
                {% if form.sex.errors %}
                <div class="invalid-feedback">
                    {% for error in form.sex.errors %}
                    {{ error }}
                    {% endfor %}
                </div>
                {% endif %}
            </div>

            <div class="form-floating mb-3">
                <textarea style="height: 100px" class="form-control {% if form.bio.errors %} is-invalid {% endif %}"
                    id="id_bio" name="bio">{{ form.bio.value|default_if_none:'' }}</textarea>
                <label for="id_bio">Bio</label>
                {% if form.bio.errors %}
                <div class="invalid-feedback">
                    {% for error in form.bio.errors %}
                    {{ error }}
                    {% endfor %}
                </div>
                {% endif %}
            </div>

            <div class="mb-3">
                <label for="id_avatar">Avatar</label>
                <input type="file" accept="image/*"
                    class="form-control {% if form.avatar.errors %} is-invalid {% endif %}" id="id_avatar"
                    name="avatar">
                <p>Currently: <a href="{{ form.avatar.value.url }}">{{ form.avatar.value|default_if_none:'' }}</a></p>
                {% if form.avatar.errors %}
                <div class="invalid-feedback">
                    {% for error in form.avatar.errors %}
                    {{ error }}
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <!-- <div class="mb-3 d-flex align-self-center">
                <p>Currently: <a href="{{ form.avatar.value.url }}">{{ form.avatar.value|default_if_none:'' }}</a></p>
                <div class="form-check ms-auto">
                    <input class="form-check-input" type="checkbox" name="avatar-clear" id="avatar-clear_id">
                    <label class="form-check-label" for="avatar-clear_id">
                        Clear
                    </label>
                </div>
            </div> -->

            <button type="submit" class="btn btn-secondary btn-sm">Update</button>
        </form>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends "no_sidebar_base.html" %}

{% block content %}
<div class="card mx-auto" style="width: 460px;">
    <div class="card-body">
        <h1 class="display-6 mb-4">Profile</h1>
        <dl class="row">
            <dt class="col-sm-5">Avatar</dt>
            <dd class="col-sm-7"><img src="{{ user.avatar.url }}" alt="" width="100" class="img-fluid rounded">
            </dd>

            <dt class="col-sm-5">Full Name</dt>
            <dd class="col-sm-7">{{ user.get_full_name }}</dd>

            <dt class="col-sm-5">Sex</dt>
            <dd class="col-sm-7">{{ user.get_sex_display }}</dd>

            <dt class="col-sm-5">Bio</dt>
            <dd class="col-sm-7">{{ user.bio }}</dd>

            <dt class="col-sm-5">Date of Birth</dt>
            <dd class="col-sm-7">{{ user.date_of_birth }}</dd>
        </dl>

        <a class="btn btn-sm btn-warning" href="{% url 'profile-edit' %}">Edit</a>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/register.html
{% extends "no_sidebar_base.html" %}

{% block content %}
<div class="card mx-auto" style="width: 460px;">
    <div class="card-body">
        <h1 class="display-6 mb-4">Register</h1>


        {% if form.non_field_errors %}
        <div class="alert alert-danger" role="alert">
            <ul class="list-unstyled">
                {% for error in form.non_field_errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}

        <form method="post">
            {% csrf_token %}
            <div class="row mb-3">
                <div class="col-md-6">
                    <div class="form-floating">
                        <input type="text" value="{{ form.first_name.value|default_if_none:'' }}"
                            class="form-control {% if form.first_name.errors %} is-invalid {% endif %}"
                            id="id_first_name" name="first_name" placeholder="First Name">
                        <label for="id_first_name">First Name</label>
                        {% if form.first_name.errors %}
                        <div class="invalid-feedback">
                            {% for error in form.first_name.errors %}
                            {{ error }}
                            {% endfor %}
                        </div>
                        {% endif %}
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-floating">
                        <input type="text" value="{{ form.last_name.value|default_if_none:'' }}"
                            class="form-control {% if form.last_name.errors %} is-invalid {% endif %}" id="id_last_name"
                            name="last_name" placeholder="Last Name">
                        <label for="id_last_name">Last Name</label>
                        {% if form.last_name.errors %}
                        <div class="invalid-feedback">
                            {% for error in form.last_name.errors %}
                            {{ error }}
                            {% endfor %}
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>

            <div class="form-floating mb-3">
                <input type="text" value="{{ form.username.value|default_if_none:'' }}"
                    class="form-control {% if form.username.errors %} is-invalid {% endif %}" id="id_username"
                    name="username" placeholder="name@example.com">
                <label for="id_username">Username</label>
                {% if form.username.errors %}
                <div class="invalid-feedback">
                    {% for error in form.username.errors %}
                    {{ error }}
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-floating mb-3">
                <input type="email" value="{{ form.email.value|default_if_none:'' }}"
                    class="form-control {% if form.email.errors %} is-invalid {% endif %}" id="id_email" name="email"
                    placeholder="name@example.com">
                <label for="id_email">Email</label>
                {% if form.email.errors %}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    {{ error }}
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-floating mb-3">
                <input type="password" value="{{ form.password1.value }}"
                    class="form-control {% if form.password1.errors %} is-invalid {% endif %}" id="id_password1"
                    name="password1" placeholder="Password">
                <label for="id_password1">Password</label>
                {% if form.password1.errors %}
                <div class="invalid-feedback">
                    {% for error in form.password1.errors %}
                    {{ error }}
                    {% endfor %}
                </div>
                {% endif %}
            </div>

            <div class="form-floating mb-3">
                <input type="password" value="{{ form.password2.value }}"
                    class="form-control {% if form.password2.errors %} is-invalid {% endif %}" id="id_password2"
                    name="password2" placeholder="Confirm Password">
                <label for="id_password2">Confirm Password</label>
                {% if form.password2.errors %}
                <div class="invalid-feedback">
                    {% for error in form.password2.errors %}
                    {{ error }}
                    {% endfor %}
                </div>
                {% endif %}
            </div>


            <div class="hstack gap-4">
                <button type="submit" value="Register" class="btn btn-primary">Register</button>
                <a class="link-primary text-decoration-none" href="{% url 'login' %}">Have an Account?</a>
            </div>
        </form>

    </div>
</div>
{% endblock %}